# Configure main menu and social menu
[[main]]
identifier = "subscribe"
name = "订阅本站"
url = "/subscribe"
weight = 1
[main.params]
icon = "bell-ringing"
newtab = true

[[main]]
identifier = "post"
name = "文章归档"
url = "/archives"
weight = 2
[main.params]
icon = "archives"
newtab = true

[[main]]
identifier = "project"
name = "我的项目"
url = "/project"
weight = 3
[main.params]
icon = "git-branch"
newtab = true

[[main]]
identifier = "links"
name = "友情链接"
url = "/links"
weight = 4
[main.params]
icon = "link"
newtab = true

[[main]]
identifier = "use"
name = "我的使用"
url = "/use"
weight = 5
[main.params]
icon = "user-cog"
newtab = true

[[main]]
identifier = "photo"
name = "摄影展集"
url = "https://photo.debuginn.com"
weight = 6
[main.params]
icon = "photo"
newtab = true

[[main]]
identifier = "profile"
name = "我的主页"
url = "https://debuginn.com"
weight = 7
[main.params]
icon = "home-star"
newtab = true

[[social]]
identifier = "github"
name = "GitHub"
weight = 1
url = "https://github.com/debuginn"
[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "x"
weight = 2
url = "https://x.com/idebuginn"
[social.params]
icon = "brand-x"

[[social]]
identifier = "zhihu"
name = "Zhihu"
weight = 4
url = "https://www.zhihu.com/people/debuginn/posts"
[social.params]
icon = "brand-zhihu"

[[social]]
identifier = "rss"
name = "Rss"
weight = 5
url = "https://blog.debuginn.com/index.xml"
[social.params]
icon = "rss"