# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
since = 2017
customText = '<a href="https://debuginn.com">ä¸»é¡µ</a>&nbsp;Â·&nbsp<a href="https://blog.debuginn.com/">åšå®¢</a>&nbsp;Â·&nbsp<a href="https://photo.debuginn.com">æ‘„å½±</a>&nbsp;Â·&nbsp<a href="/project/">é¡¹ç›®</a>&nbsp;Â·&nbsp<a href="/about/">å…³äº</a>'

[dateFormat]
published = "2023/10/15"
lastUpdated = "2023/10/15 15:04 MST"

[sidebar]
emoji = "ğŸŒ"
subtitle = "æ°¸è¿œç›¸ä¿¡ç¾å¥½çš„äº‹æƒ…å³å°†å‘ç”Ÿ"

[sidebar.avatar]
enabled = true
local = false
src = "https://webp.debuginn.com/20250506fT6oPc.jpg"

[article]
headingAnchor = true
math = false
toc = true
readingTime = true

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "wechat"

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 18

[[widgets.homepage]]
type = "ad"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 2

[[widgets.page]]
type = "search"

[[widgets.page]]
type = "toc"

[[widgets.page]]
type = "wechat"

[[widgets.page]]
type = "ad"

[opengraph.twitter]
site = "idebuginn"
card = "summary_large_image"

[defaultImage.opengraph]
enabled = true
local = false
src = "https://webp.debuginn.com/20250506fT6oPc.jpg"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "debuginn/blog"
repoID = "R_kgDOI_rNgg"
category = "General"
categoryID = "DIC_kwDOI_rNgs4CUT4j"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 0
lang = "zh-CN"
defaultCommentOrder = "newest"
