# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true

[footer]
since = 2017
customText = '<a href="https://debuginn.com">ä¸»é¡µ</a>&nbsp;Â·&nbsp<a href="https://blog.debuginn.com/">åšå®¢</a>&nbsp;Â·&nbsp<a href="https://photo.debuginn.com">æ‘„å½±</a>&nbsp;Â·&nbsp<a href="/project/">é¡¹ç›®</a>&nbsp;Â·&nbsp<a href="/use/">ä½¿ç”¨</a>&nbsp;Â·&nbsp<a href="/about/">å…³äº</a>'

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"

[sidebar]
emoji = "ğŸŒ"
subtitle = "æ°¸è¿œç›¸ä¿¡ç¾å¥½çš„äº‹æƒ…å³å°†å‘ç”Ÿ"

[sidebar.avatar]
enabled = true
local = false
src = "https://static.debuginn.com/20250506fT6oPc.jpg"

[article]
headingAnchor = true
math = false
toc = true
readingTime = true

[article.license]
enabled = true
default = "æœ¬ä½œå“é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å - éå•†ä¸šæ€§ä½¿ç”¨ - ç›¸åŒæ–¹å¼å…±äº« 4.0 è®¸å¯åè®®è¿›è¡Œè®¸å¯ï¼Œå•†ä¸šè½¬è½½è¯·è”ç³»æˆæƒã€‚"

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "wechat"

[[widgets.homepage]]
type = "popular"

[[widgets.homepage]]
type = "promote"

[[widgets.homepage]]
type = "donation"

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 32

[[widgets.page]]
type = "search"

[[widgets.page]]
type = "wechat"

[[widgets.page]]
type = "toc"

[[widgets.page]]
type = "donation"

[[widgets.page]]
type = "promote"

[[widgets.page]]
type = "popular"

[opengraph.twitter]
site = "idebuginn"
card = "summary_large_image"

[defaultImage.opengraph]
enabled = true
local = false
src = "https://static.debuginn.com/20250506fT6oPc.jpg"

[colorScheme]
toggle = true
default = "auto"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true

## Comments
[comments]
enabled = true
provider = "giscus"

[comments.giscus]
repo = "debuginn/blog"
repoID = "R_kgDOI_rNgg"
category = "General"
categoryID = "DIC_kwDOI_rNgs4CUT4j"
mapping = "pathname"
lightTheme = "light"
darkTheme = "dark"
reactionsEnabled = 1
emitMetadata = 0
lang = "zh-CN"

[donation]
title = "èµèµ"
qrcode = "https://static.debuginn.com/20250807C6FEAA.png"

[[donation.cryptos]]
label = "SOL"
address = "5LupLo8NuTfC411zAPo6UZTuasoTHaueuptVyGKmsdBV"

[[donation.cryptos]]
label = "BTC"
address = "bc1quwwdn506pknw8tl8ynrgjql2350cpmxmgjttdp"

[[donation.cryptos]]
label = "ETH"
address = "0xd06a56704eCb1EEe65AbcAa3101d88E2a8225a4E"

[promote]
title = "æ¨å¹¿"

[[promote.items]]
href = "/p/mi-work/"
icon = "briefcase"
text = "æ¥å°ç±³ï¼Œä¸€èµ·ç©ï¼æ ¡æ‹›ã€ç¤¾æ‹›å‡å¯å†…æ¨ï¼"

[[promote.items]]
href = "https://cloud.siliconflow.cn/i/ftshEbe9"
icon = "ai"
text = "ç¡…åŸºæµåŠ¨ï¼Œä¸€ç«™å¼å¤§æ¨¡å‹äº‘æœåŠ¡å¹³å°ã€‚"
target = "_blank"

[[promote.items]]
href = "https://www.xflash.live/#/register?code=GZRNxKBh"
icon = "network"
text = "XFlash Cloudï¼Œç¨³å®šå¥½ç”¨é€Ÿåº¦å¿«ã€‚"
target = "_blank"

[popular]
title = "çƒ­é—¨"

[[popular.items]]
href = "/p/work-5-years/"
icon = "brand-linkedin"
text = "å…¥èŒ 5 å‘¨å¹´ï¼Œæˆ‘å’Œå°ç±³çš„ 5 å‘¨å¹´"
views = "1.2k"

[[popular.items]]
href = "/p/financial-hongkong-card/"
icon = "wallet"
text = "æ¸¯å¡å¼€å¡æŒ‡å—"
views = "856"

[[popular.items]]
href = "/use/"
icon = "devices"
text = "æˆ‘çš„ä½¿ç”¨"
views = "437"

[[popular.items]]
href = "/p/travel-bohainan/"
icon = "car"
text = "æ¸¸è®° äº”ä¸€ç¯æ¸¤æµ·å—æµ·å²¸è‡ªé©¾ä¹‹æ—…"
views = "326"

[[popular.items]]
href = "/p/travel-dawanqu/"
icon = "building-airport"
text = "æ¸¸è®° æ¸¯æ¾³æ·±å¤§æ¹¾åŒºé£çƒä¸­æ—…ç¨‹"
views = "289"
